---

quorumFlags:
  removeGenesisOnDelete: true

cluster:
  provider: aws  # choose from: local | aws
  cloudNativeServices: true # set to true to use Cloud Native Services (SecretsManager and IAM for AWS)

aws:
  # the aws cli commands uses the name 'quorum-node-secrets-sa' so only change this if you altered the name
  serviceAccountName: quorum-node-secrets-sa
  # the region you are deploying to
  region: us-east-1

# the raw Genesis config
# rawGenesisConfig.blockchain.nodes set the number of validators/signers
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: qbft
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    gasLimit: '0xf7b760' 
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
  blockchain:
    nodes:
      generate: true
      overwrite: false
      count: 4
    accountPassword: 'password'

image:
  repository: consensys/quorum-k8s-hooks
  tag: qgt-0.2.6
  pullPolicy: IfNotPresent
