image:
  explorer:
    repository: consensys/quorum-explorer
    tag: e175e0b
    pullPolicy: Always #IfNotPresent

resources:
  requests:
    cpu: 1000m
    memory: 1G

# This contains the quorum-dev-quickstart test accounts but can be changed to the generated member accounts or your own choice
explorerConfig: |
  {
  "algorithm": "qbft",
  "nodes": [{
      "name": "validator1",
      "client": "besu",
      "rpcUrl": "http://besu-node-validator-1.besu.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator2",
      "client": "besu",
      "rpcUrl": "http://besu-node-validator-2.besu.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator3",
      "client": "besu",
      "rpcUrl": "http://besu-node-validator-3.besu.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator4",
      "client": "besu",
      "rpcUrl": "http://besu-node-validator-4.besu.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "member1",
      "client": "besu",
      "rpcUrl": "http://besu-node-member-1.besu.svc.cluster.local:8545",
      "privateTxUrl": "http://besu-node-member-1.besu.svc.cluster.local:9080",
      "privateKey": "0x6b5ee9334c05d09eb935d90b3227e6922fcc70dca315f9a970973b7ade7e58ca",
      "accountAddress": "0x16b66b29c7a88cb91f51946db99de77e21dcb155"
    },
    {
      "name": "member2",
      "client": "besu",
      "rpcUrl": "http://besu-node-member-2.besu.svc.cluster.local:8545",
      "privateTxUrl": "http://besu-node-member-2.besu.svc.cluster.local:9080",
      "privateKey": "0x7e3446c09086c76e50e433f479da1a745b34b4ec32e38b8af83bac6654105e9b",
      "accountAddress": "0xee1d18f45ea4fcb8fe99792dd257731c56fac722"
    }
  ]
  }

explorerEnvConfig: |-
  QE_BASEPATH="/explorer"
  QE_CONFIG_PATH="/app/config.json"
  NODE_ENV=production

  DISABLE_AUTH=true

  NEXTAUTH_URL=http://localhost:25000
  NEXTAUTH_URL_INTERNAL=http://localhost:25000
  NEXTAUTH_SECRET=
  # To generate NEXTAUTH_SECRET: `openssl rand -hex 32` or go to https://generate-secret.now.sh/32

  local_username=
  local_password=

  GITHUB_ID=
  GITHUB_SECRET=

  AUTH0_ID=
  AUTH0_SECRET=
  AUTH0_DOMAIN=

  FACEBOOK_ID=
  FACEBOOK_SECRET=

  GOOGLE_ID=
  GOOGLE_SECRET=

  TWITTER_ID=
  TWITTER_SECRET=

  GITLAB_CLIENT_ID=
  GITLAB_CLIENT_SECRET=

  AZURE_AD_CLIENT_ID=
  AZURE_AD_CLIENT_SECRET=
  AZURE_AD_TENANT_ID=

  ATLASSIAN_CLIENT_ID=
  ATLASSIAN_CLIENT_SECRET=

  COGNITO_CLIENT_ID=
  COGNITO_CLIENT_SECRET=
  COGNITO_ISSUER=

  OKTA_CLIENT_ID=
  OKTA_CLIENT_SECRET=
  OKTA_ISSUER=

  SLACK_CLIENT_ID=
  SLACK_CLIENT_SECRET=